'use client';

import { Bot, Star, UserCheck, HelpCircle } from 'lucide-react';
import type { AnalysisSource } from '@/lib/types';

interface AnalysisSourceLabelProps {
  source: AnalysisSource;
  /** Show the icon before the label */
  showIcon?: boolean;
  /** Size variant */
  size?: 'sm' | 'md';
  /** Show detailed tooltip with help icon */
  showTooltip?: boolean;
  /** For Google Maps rating source - show the actual rating value */
  ratingValue?: number | null;
}

const sourceConfig: Record<
  AnalysisSource,
  {
    label: string;
    shortLabel: string;
    description: string;
    tooltipText: string;
    icon: React.ComponentType<{ className?: string }>;
    colorClass: string;
    bgClass: string;
    borderClass: string;
  }
> = {
  model: {
    label: 'ประมวลผลด้วย AI',
    shortLabel: 'AI Model',
    description: 'วิเคราะห์โดยโมเดล AI',
    tooltipText: 'ผลลัพธ์นี้ได้จากการวิเคราะห์อัตโนมัติโดยโมเดล Machine Learning (WangchanBERTa / PhayathaiiBERT)',
    icon: Bot,
    colorClass: 'text-purple-700',
    bgClass: 'bg-purple-50',
    borderClass: 'border-purple-200',
  },
  rating: {
    label: 'แปลงจากคะแนนรีวิว',
    shortLabel: 'จากคะแนน',
    description: 'แปลงจากคะแนนรีวิวที่ผู้ใช้ให้',
    tooltipText: 'ผลลัพธ์นี้แปลงมาจากคะแนนรีวิว (1-2 = เชิงลบ, 3 = เป็นกลาง, 4-5 = เชิงบวก)',
    icon: Star,
    colorClass: 'text-amber-700',
    bgClass: 'bg-amber-50',
    borderClass: 'border-amber-200',
  },
  user: {
    label: 'แก้ไขโดยผู้ใช้',
    shortLabel: 'แก้ไขเอง',
    description: 'แก้ไขด้วยตนเองโดยผู้ดูแลระบบ',
    tooltipText: 'ผลลัพธ์นี้ถูกแก้ไขด้วยตนเองโดยผู้ดูแลระบบ ไม่ใช่ผลจากโมเดล AI',
    icon: UserCheck,
    colorClass: 'text-blue-700',
    bgClass: 'bg-blue-50',
    borderClass: 'border-blue-200',
  },
};

/**
 * AnalysisSourceLabel - Display the source of an analysis result
 *
 * Shows where the sentiment/intent/aspect label came from:
 * - model: Generated by AI model processing
 * - rating: Mapped from star rating (e.g., Google Maps reviews)
 * - user: Manually corrected by a user
 *
 * UX: Uses both color AND text labels for clarity
 * Optionally shows a tooltip with detailed explanation
 */
export function AnalysisSourceLabel({
  source,
  showIcon = true,
  size = 'sm',
  showTooltip = true,
  ratingValue,
}: AnalysisSourceLabelProps) {
  const config = sourceConfig[source];

  if (!config) return null;

  const Icon = config.icon;
  const sizeClasses = size === 'sm'
    ? 'text-xs px-2 py-1'
    : 'text-sm px-2.5 py-1.5';
  const iconSize = size === 'sm' ? 'w-3 h-3' : 'w-4 h-4';

  // Build the label text
  let labelText = config.label;
  if (source === 'rating' && ratingValue !== null && ratingValue !== undefined) {
    labelText = `${config.shortLabel} (${ratingValue} ดาว)`;
  }

  return (
    <div className="inline-flex items-center gap-1.5 group relative">
      {/* Main Badge */}
      <span
        className={`inline-flex items-center gap-1.5 rounded-md border ${config.bgClass} ${config.colorClass} ${config.borderClass} ${sizeClasses} font-medium`}
      >
        {showIcon && <Icon className={iconSize} />}
        <span>{labelText}</span>
      </span>

      {/* Tooltip Icon & Popup */}
      {showTooltip && (
        <div className="relative">
          <HelpCircle
            className={`${iconSize} text-gray-400 hover:text-gray-600 cursor-help`}
          />
          {/* Tooltip Popup */}
          <div className="absolute bottom-full right-0 mb-2 w-64 p-3 bg-gray-900 text-white text-xs rounded-lg shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-50">
            <div className="font-semibold mb-1 flex items-center gap-1.5">
              <Icon className="w-3.5 h-3.5" />
              {config.description}
            </div>
            <p className="text-gray-300 leading-relaxed">
              {config.tooltipText}
            </p>
            {/* Tooltip Arrow */}
            <div className="absolute -bottom-1 right-3 w-2 h-2 bg-gray-900 rotate-45" />
          </div>
        </div>
      )}
    </div>
  );
}

/**
 * AnalysisSourceBadge - Compact version for inline display
 * Shows only icon + short label without tooltip
 */
export function AnalysisSourceBadge({
  source,
  size = 'sm',
}: {
  source: AnalysisSource;
  size?: 'sm' | 'md';
}) {
  const config = sourceConfig[source];
  if (!config) return null;

  const Icon = config.icon;
  const sizeClasses = size === 'sm' ? 'text-xs px-1.5 py-0.5' : 'text-sm px-2 py-1';
  const iconSize = size === 'sm' ? 'w-3 h-3' : 'w-4 h-4';

  return (
    <span
      className={`inline-flex items-center gap-1 rounded ${config.bgClass} ${config.colorClass} ${sizeClasses}`}
      title={config.tooltipText}
    >
      <Icon className={iconSize} />
      <span>{config.shortLabel}</span>
    </span>
  );
}

/**
 * Get the description text for an analysis source
 */
export function getAnalysisSourceDescription(source: AnalysisSource): string {
  return sourceConfig[source]?.description || source;
}

/**
 * Get the full tooltip text for an analysis source
 */
export function getAnalysisSourceTooltip(source: AnalysisSource): string {
  return sourceConfig[source]?.tooltipText || source;
}
