"""Initial migration - create feedback and analysis tables

Revision ID: e7dd65e74927
Revises: 
Create Date: 2025-12-14 13:48:29.916023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7dd65e74927'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_records',
    sa.Column('source_type', sa.String(length=50), nullable=False, comment='Source type: email, instagram, facebook, google_form, google_maps, manual'),
    sa.Column('source_id', sa.String(length=255), nullable=True, comment='Unique ID from source (e.g., comment_id, email_id)'),
    sa.Column('text_content', sa.Text(), nullable=False, comment='Main text content of the feedback'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Source-specific raw data'),
    sa.Column('created_at_source', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Original timestamp from source'),
    sa.Column('processing_status', sa.String(length=20), server_default='pending', nullable=False, comment='Status: pending, processing, completed, failed'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_feedback_source')
    )
    op.create_index('idx_feedback_created_at', 'feedback_records', ['created_at'], unique=False)
    op.create_index('idx_feedback_processing_status', 'feedback_records', ['processing_status'], unique=False)
    op.create_index('idx_feedback_source_type', 'feedback_records', ['source_type'], unique=False)
    op.create_table('aspect_sentiment_results',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('aspect', sa.String(length=50), nullable=False, comment='Aspect: equipment, staff, cleanliness, atmosphere, price, location, programs, amenities'),
    sa.Column('sentiment', sa.String(length=20), nullable=False, comment='Sentiment: positive, neutral, negative, none'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Confidence score (0-1)'),
    sa.Column('created_at', sa.String(), server_default='NOW()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aspect_sentiment_aspect', 'aspect_sentiment_results', ['aspect'], unique=False)
    op.create_index('idx_aspect_sentiment_feedback_id', 'aspect_sentiment_results', ['feedback_id'], unique=False)
    op.create_index('idx_aspect_sentiment_sentiment', 'aspect_sentiment_results', ['sentiment'], unique=False)
    op.create_index(op.f('ix_aspect_sentiment_results_feedback_id'), 'aspect_sentiment_results', ['feedback_id'], unique=False)
    op.create_table('intent_results',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=False, comment='Intent: feedback, question, complaint, off_topic'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Confidence score (0-1)'),
    sa.Column('created_at', sa.String(), server_default='NOW()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intent_feedback_id', 'intent_results', ['feedback_id'], unique=False)
    op.create_index('idx_intent_intent', 'intent_results', ['intent'], unique=False)
    op.create_index(op.f('ix_intent_results_feedback_id'), 'intent_results', ['feedback_id'], unique=False)
    op.create_table('sentiment_results',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False, comment='Sentiment: positive, neutral, negative'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Confidence score (0-1)'),
    sa.Column('created_at', sa.String(), server_default='NOW()', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sentiment_feedback_id', 'sentiment_results', ['feedback_id'], unique=False)
    op.create_index('idx_sentiment_sentiment', 'sentiment_results', ['sentiment'], unique=False)
    op.create_index(op.f('ix_sentiment_results_feedback_id'), 'sentiment_results', ['feedback_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_results_feedback_id'), table_name='sentiment_results')
    op.drop_index('idx_sentiment_sentiment', table_name='sentiment_results')
    op.drop_index('idx_sentiment_feedback_id', table_name='sentiment_results')
    op.drop_table('sentiment_results')
    op.drop_index(op.f('ix_intent_results_feedback_id'), table_name='intent_results')
    op.drop_index('idx_intent_intent', table_name='intent_results')
    op.drop_index('idx_intent_feedback_id', table_name='intent_results')
    op.drop_table('intent_results')
    op.drop_index(op.f('ix_aspect_sentiment_results_feedback_id'), table_name='aspect_sentiment_results')
    op.drop_index('idx_aspect_sentiment_sentiment', table_name='aspect_sentiment_results')
    op.drop_index('idx_aspect_sentiment_feedback_id', table_name='aspect_sentiment_results')
    op.drop_index('idx_aspect_sentiment_aspect', table_name='aspect_sentiment_results')
    op.drop_table('aspect_sentiment_results')
    op.drop_index('idx_feedback_source_type', table_name='feedback_records')
    op.drop_index('idx_feedback_processing_status', table_name='feedback_records')
    op.drop_index('idx_feedback_created_at', table_name='feedback_records')
    op.drop_table('feedback_records')
    # ### end Alembic commands ###
